#!/usr/bin/env tclsh
# SPDX-License-Identifier: Apache-2.0
# Copyright 2024-2026 LogiMentor S.r.l.

# -----------------------------------------------------------------------------
# Radiant importer:
#  - Read existing Radiant project (.rdf)
#  - Copy/symlink sources into your standard tree
#  - Recreate a clean .rdf in impl/work/radiant/<name>
#  - Optionally emit config/project.yaml
#
# Usage:
#   radiantc aurig_build/radiant/import.tcl <radiant_project_folder> \
#     --dest=./temp/mytest --name=my_port --mode=copy|link --yaml --verbose --force
# -----------------------------------------------------------------------------

proc _puts {m} { puts $m }
proc _warn {m} { puts "WARN: $m" }
proc _die  {m} { puts stderr "ERROR: $m"; exit 2 }
proc npath {p} { return [string map {"\\" "/"} [file normalize $p]] }
proc ensure_dir {d} { if {![file isdirectory $d]} { file mkdir $d }; return [file normalize $d] }
proc joinf {args} { return [npath [eval file join $args]] }

# Minimal .rdf parser (XML-like): get impl name, top, device, and sources
proc parse_rdf {rdf_path} {
    set R [dict create impl "impl1" top "" device "" src {}]
    set f [open $rdf_path r]
    while {[gets $f line] >= 0} {
        set s [string trim $line]
        if {[regexp {Implementation\s+name="([^"]+)"} $s -> impl]} { dict set R impl $impl }
        if {[regexp {top="([^"]+)"} $s -> top]} { dict set R top $top }
        if {[regexp {device="([^"]+)"} $s -> dev]} { dict set R device $dev }
        if {[regexp {File\s+path="([^"]+)"} $s -> fp]} { dict lappend R src $fp }
    }
    close $f
    return $R
}

proc stage {src_root dst_root p mode} {
    set pt [file pathtype $p]
    if {$pt eq "relative" || $pt eq "volumerelative"} { set p [joinf $src_root $p] }
    set abs [npath $p]
    if {![file exists $abs]} { _warn "missing: $p"; return "" }
    set dst_dir [ensure_dir [file join $dst_root [file tail [file dirname $abs]]]]
    set dst [file normalize [file join $dst_dir [file tail $abs]]]
    if {$mode eq "link"} {
        if {[catch {file link -symbolic $dst $abs} err]} {
            _warn "symlink failed ($err); copying $abs"
            file copy -force $abs $dst
        }
    } else { file copy -force $abs $dst }
    return [npath $dst]
}

proc write_yaml {dest name top part} {
    set cfgd [ensure_dir [joinf $dest config]]
    set y [joinf $cfgd project.yaml]
    set fh [open $y w]
    puts $fh "# Generated by aurig_build/radiant/import.tcl"
    puts $fh "project_name: $name"
    puts $fh "top: $top"
    puts $fh "device:"
    puts $fh "  part: $part"
    puts $fh ""
    puts $fh "file_sets:"
    puts $fh "  - name: default"
    puts $fh "    lib: work"
    puts $fh "    std: 2008"
    puts $fh "    files:"
    puts $fh "      - \"src/hdl/**/*.vhd\""
    puts $fh "      - \"src/hdl/**/*.v\""
    puts $fh "      - \"src/hdl/**/*.sv\""
    puts $fh ""
    puts $fh "constraints:"
    puts $fh "  xdc_files:"
    puts $fh "    - \"constraints/**/*.xdc\""
    close $fh
    return $y
}

proc write_rdf {workdir name impl top device vhdl_files v_files sv_files other} {
    cd $workdir
    if {[file exists "${name}.rdf"]} { file delete -force "${name}.rdf" }
    prj_create -force "${name}.rdf"
    prj_add_impl $impl
    prj_set_impl_opt -impl $impl top $top         ;# Radiant top setter 
    prj_set_device -impl $impl $device
    foreach f $vhdl_files { prj_add_source $f -lib work }
    foreach f $v_files    { prj_add_source $f }
    foreach f $sv_files   { prj_add_source $f }
    foreach f $other      { prj_add_source $f }
    prj_save
    return [file normalize "${name}.rdf"]
}

# CLI
if {$argc < 1} {
    puts "Usage: radiantc aurig_build/radiant/import.tcl <rdf_folder> --dest=./temp/test --name=foo --mode=copy|link --yaml --verbose --force"
    exit 1
}
set src [npath [lindex $argv 0]]
set flags [lrange $argv 1 end]
set dest [npath "."]
set name ""; set mode "copy"; set verbose 0; set force 0; set make_yaml 1

foreach a $flags {
    if {[regexp {^--dest=(.+)} $a -> v]}   { set dest [npath $v]; continue }
    if {[regexp {^--name=(.+)} $a -> v]}   { set name $v;        continue }
    if {[regexp {^--mode=(copy|link)$} $a -> v]} { set mode $v;  continue }
    if {$a eq "--verbose"}                 { set verbose 1;       continue }
    if {$a eq "--no-yaml"}                 { set make_yaml 0;     continue }
    if {$a eq "--yaml"}                    { set make_yaml 1;     continue }
    if {$a eq "--force"}                   { set force 1;         continue }
}

if {![file isdirectory $src]} { _die "Folder not found: $src" }
set rdf [lindex [glob -nocomplain -directory $src *.rdf] 0]
if {$rdf eq ""} { _die "No .rdf found under $src" }
set M [parse_rdf $rdf]
set impl [dict get $M impl]
set top  [dict get $M top]
set part [dict get $M device]
if {$top eq ""}  { _die "Top not found in RDF" }
if {$part eq ""} { _die "Device not found in RDF" }
if {$name eq ""} { set name [file rootname [file tail $rdf]] }

# Prepare destinations
if {[file exists $dest] && ![file isdirectory $dest]} { _die "--dest exists and not a directory" }
if {[file isdirectory $dest] && !$force} {
    set entries [glob -nocomplain -directory $dest *]
    if {[llength $entries] > 0} {
        puts -nonewline "Destination '$dest' exists and is not empty. Overwrite/merge? \[y/N]: "
        flush stdout
        if {[gets stdin ans] < 0} { set ans "n" }
        set ans [string tolower [string trim $ans]]
        if {![string match "y*" $ans]} { _die "Aborted by user." }
    }
}
set d_hdl [ensure_dir [joinf $dest src hdl]]
set d_con [ensure_dir [joinf $dest constraints]]
set d_ip  [ensure_dir [joinf $dest ip]]
set d_wrk [ensure_dir [joinf $dest impl work radiant $name]]

# Stage
set staged_vhdl {}; set staged_v {}; set staged_sv {}; set staged_other {}
foreach p [dict get $M src] {
    set ext [string tolower [file extension $p]]
    switch -- $ext {
        ".vhd" - ".vhdl" { lappend staged_vhdl [stage $src $d_hdl $p $mode] }
        ".v"             { lappend staged_v     [stage $src $d_hdl $p $mode] }
        ".sv"            { lappend staged_sv    [stage $src $d_hdl $p $mode] }
        ".xdc"           { stage $src $d_con $p $mode }
        default          { stage $src $d_ip  $p $mode }
    }
}

# Recreate project
set out_rdf [write_rdf $d_wrk $name $impl $top $part \
    $staged_vhdl $staged_v $staged_sv $staged_other]
_puts "RDF written: $out_rdf"

if {$make_yaml} {
    set y [write_yaml $dest $name $top $part]
    _puts "YAML written: $y"
}
return 0
